# -*- coding: utf-8 -*-
"""MyProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qrAUdk-Ck4HPCP149gSfWcDjzYwqMAh
"""

from google.colab import drive
drive.mount('/content/drive')

import os
PROJECT_DIR = "/content/drive/MyDrive/NetworkTrafficClassifier"
os.makedirs(PROJECT_DIR, exist_ok=True)
os.chdir(PROJECT_DIR)

import sys
sys.path.append(PROJECT_DIR)
print(f"Working directory: {os.getcwd()}")
print("🚀 Project loaded from Drive")

!pip install -q imbalanced-learn

# Commented out IPython magic to ensure Python compatibility.
# %cd $PROJECT_DIR

!mkdir -p $PROJECT_DIR
!mv /content/configs /content/data /content/outputs /content/src $PROJECT_DIR/

# Install project dependencies not pre-installed in Colab
!pip install -q scapy pyshark rich pyyaml plotly

# Verify key packages
import tensorflow as tf
import sklearn
import numpy as np
import pandas as pd

print(f"TensorFlow: {tf.__version__}")
print(f"Scikit-learn: {sklearn.__version__}")
print(f"NumPy: {np.__version__}")
print(f"GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}")

import os

PROJECT_FILES = [
    "src/__init__.py",
    "src/features/__init__.py",
    "src/models/__init__.py",
    "src/utils/__init__.py",
    "src/capture/__init__.py",
    "configs/",
    "data/raw/",
    "data/processed/",
    "outputs/models/",
    "outputs/plots/",
    "outputs/reports/",
]

for path in PROJECT_FILES:
    if path.endswith("/"):
        os.makedirs(path, exist_ok=True)
    else:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if not os.path.exists(path):
            open(path, "w").close()

print("Project structure created.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import joblib
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
from sklearn.preprocessing import StandardScaler, LabelEncoder, RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import (
    classification_report, accuracy_score, f1_score,
    confusion_matrix, silhouette_score, adjusted_rand_score
)
from sklearn.decomposition import PCA

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

print("All imports successful!")
print(f"GPU: {tf.config.list_physical_devices('GPU')}")

DATASET_MODE = "csv"
DATASET_PATH = "/content/drive/MyDrive/NetworkTrafficClassifier/data/raw/CIC-IDS-201"
N_SYNTHETIC_SAMPLES = 8000
N_CLASSES = 6
RANDOM_STATE = 42

FLOW_FEATURES = [
    "fwd_packet_count", "bwd_packet_count",
    "total_fwd_bytes", "total_bwd_bytes",
    "fwd_pkt_len_mean", "fwd_pkt_len_std", "fwd_pkt_len_min", "fwd_pkt_len_max",
    "bwd_pkt_len_mean", "bwd_pkt_len_std", "bwd_pkt_len_min", "bwd_pkt_len_max",
    "flow_duration", "flow_bytes_per_sec", "flow_pkts_per_sec",
    "iat_mean", "iat_std", "iat_min", "iat_max",
    "fwd_iat_mean", "fwd_iat_std", "fwd_iat_min", "fwd_iat_max",
    "bwd_iat_mean", "bwd_iat_std", "bwd_iat_min", "bwd_iat_max",
    "fwd_bwd_byte_ratio", "fwd_bwd_pkt_ratio",
    "header_ratio", "payload_ratio",
    "active_mean", "idle_mean",
]
print(f"Feature count: {len(FLOW_FEATURES)}")

import os
import glob

# Check what's in your Drive
base = "/content/drive/MyDrive/NetworkTrafficClassifier/data/raw"
print("Contents of raw/:")
for item in os.listdir(base):
    print(f"  {item}")

cic_path = "/content/drive/MyDrive/NetworkTrafficClassifier/data/raw/CIC-IDS-201"
print("Contents of CIC-IDS-201/:")
for item in os.listdir(cic_path):
    print(f"  {item}")

# ══════════════════════════════════════════════════════════════
# DATA LOADING — CIC-IDS-2017
# ══════════════════════════════════════════════════════════════
import glob

# CIC-IDS-2017 column mapping — columns already have meaningful names
CIC_COL_MAP = {
    " Total Fwd Packets":               "fwd_packet_count",
    " Total Backward Packets":          "bwd_packet_count",
    " Total Length of Fwd Packets":     "total_fwd_bytes",
    " Total Length of Bwd Packets":     "total_bwd_bytes",
    " Fwd Packet Length Mean":          "fwd_pkt_len_mean",
    " Fwd Packet Length Std":           "fwd_pkt_len_std",
    " Fwd Packet Length Min":           "fwd_pkt_len_min",
    " Fwd Packet Length Max":           "fwd_pkt_len_max",
    " Bwd Packet Length Mean":          "bwd_pkt_len_mean",
    " Bwd Packet Length Std":           "bwd_pkt_len_std",
    " Bwd Packet Length Min":           "bwd_pkt_len_min",
    " Bwd Packet Length Max":           "bwd_pkt_len_max",
    " Flow Duration":                   "flow_duration",
    " Flow Bytes/s":                    "flow_bytes_per_sec",
    " Flow Packets/s":                  "flow_pkts_per_sec",
    " Flow IAT Mean":                   "iat_mean",
    " Flow IAT Std":                    "iat_std",
    " Flow IAT Min":                    "iat_min",
    " Flow IAT Max":                    "iat_max",
    " Fwd IAT Mean":                    "fwd_iat_mean",
    " Fwd IAT Std":                     "fwd_iat_std",
    " Fwd IAT Min":                     "fwd_iat_min",
    " Fwd IAT Max":                     "fwd_iat_max",
    " Bwd IAT Mean":                    "bwd_iat_mean",
    " Bwd IAT Std":                     "bwd_iat_std",
    " Bwd IAT Min":                     "bwd_iat_min",
    " Bwd IAT Max":                     "bwd_iat_max",
    " Fwd Header Length":               "fwd_header_len",
    " Bwd Header Length":               "bwd_header_len",
    " Average Packet Size":             "avg_pkt_size",
    " Avg Fwd Segment Size":            "fwd_seg_size_mean",
    " Avg Bwd Segment Size":            "bwd_seg_size_mean",
    " Label":                           "label",
}

# Load all CSV files from CIC-IDS-2017 folder
csv_files = sorted(glob.glob(
    "/content/drive/MyDrive/NetworkTrafficClassifier/data/raw/CIC-IDS-201/*.csv"
))
print(f"Found {len(csv_files)} CSV files:")
for f in csv_files:
    print(f"  {f.split('/')[-1]}")

parts = []
for fpath in csv_files:
    try:
        tmp = pd.read_csv(fpath, low_memory=False)
        tmp.columns = tmp.columns.str.strip()   # strip whitespace from col names
        parts.append(tmp)
        print(f"  Loaded {fpath.split('/')[-1]}: {tmp.shape}")
    except Exception as e:
        print(f"  ⚠️  Failed {fpath.split('/')[-1]}: {e}")

df_raw = pd.concat(parts, ignore_index=True)
print(f"\nTotal rows: {len(df_raw)}")

# Rename columns
df_raw.columns = df_raw.columns.str.strip()
df_raw = df_raw.rename(columns={k.strip(): v for k, v in CIC_COL_MAP.items()})

# Fix label column
df_raw["label"] = df_raw["label"].astype(str).str.strip()

print(f"\nRaw label distribution:")
print(df_raw["label"].value_counts())

# ── Derive missing features from available columns ────────────
# fwd_bwd_byte_ratio
df_raw["fwd_bwd_byte_ratio"] = (
    df_raw["total_fwd_bytes"] / df_raw["total_bwd_bytes"].replace(0, 1)
)
df_raw["fwd_bwd_pkt_ratio"] = (
    df_raw["fwd_packet_count"] / df_raw["bwd_packet_count"].replace(0, 1)
)

# header/payload ratio
total_bytes   = df_raw["total_fwd_bytes"] + df_raw["total_bwd_bytes"]
total_packets = df_raw["fwd_packet_count"] + df_raw["bwd_packet_count"]
df_raw["header_ratio"]  = ((total_packets * 40) / total_bytes.replace(0, 1)).clip(0, 1)
df_raw["payload_ratio"] = (1 - df_raw["header_ratio"]).clip(0, 1)

# active/idle from duration
dur = pd.to_numeric(df_raw["flow_duration"], errors="coerce").fillna(0)
df_raw["active_mean"] = dur * 0.7
df_raw["idle_mean"]   = dur * 0.3

# ── Normalize labels ──────────────────────────────────────────
# CIC-IDS-2017 uses "BENIGN" for normal traffic
LABEL_MAP = {
    "BENIGN":                          "Normal",
    "DoS Hulk":                        "DoS",
    "DoS GoldenEye":                   "DoS",
    "DoS slowloris":                   "DoS",
    "DoS Slowhttptest":                "DoS",
    "Heartbleed":                      "DoS",
    "DDoS":                            "DoS",
    "FTP-Patator":                     "Brute Force",
    "SSH-Patator":                     "Brute Force",
    "Bot":                             "Reconnaissance",   # merge into Recon
    "PortScan":                        "Reconnaissance",
}

# Web Attack labels have encoding issues — handle separately after loading
# Add this block right after df_raw["label"] = df_raw["label"].replace(LABEL_MAP)
df_raw["label"] = df_raw["label"].apply(
    lambda x: "Web Attack" if "Web Attack" in str(x) else x
)
df_raw["label"] = df_raw["label"].replace(LABEL_MAP)
df_raw["label"] = df_raw["label"].replace({"nan": "Normal", "": "Normal"})

print(f"\nNormalized label distribution:")
print(df_raw["label"].value_counts())

# ── Sample per class ──────────────────────────────────────────
MAX_PER_CLASS = 40000
MIN_SAMPLES   = 500

sampled_parts = []
for label_name, group in df_raw.groupby("label"):
    if len(group) >= MIN_SAMPLES:
        sampled_parts.append(
            group.sample(n=min(MAX_PER_CLASS, len(group)), random_state=RANDOM_STATE)
        )
    else:
        print(f"Dropping '{label_name}' — only {len(group)} samples")

df = pd.concat(sampled_parts).sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)

# Fill any missing FLOW_FEATURES with 0
for feat in FLOW_FEATURES:
    if feat not in df.columns:
        df[feat] = 0.0

N_CLASSES = df["label"].nunique()
print(f"\nFinal shape: {df.shape}")
print(f"Classes ({N_CLASSES}): {df['label'].value_counts().to_dict()}")

# Check which FLOW_FEATURES columns are still all zero
zero_cols = [f for f in FLOW_FEATURES if f in df.columns and (df[f] == 0).all()]
print(f"Still all-zero features: {zero_cols}")

# Also check a sample of the key derived features
print(df[["fwd_iat_std", "fwd_iat_max", "header_ratio", "payload_ratio", "active_mean"]].describe())

# ══════════════════════════════════════════════════════════════
# VISUALIZATION
# ══════════════════════════════════════════════════════════════

# Fix inf values before visualization
df["flow_bytes_per_sec"] = df["flow_bytes_per_sec"].replace([np.inf, -np.inf], np.nan).fillna(0)
df["flow_pkts_per_sec"]  = df["flow_pkts_per_sec"].replace([np.inf, -np.inf], np.nan).fillna(0)
df["iat_mean"]           = df["iat_mean"].replace([np.inf, -np.inf], np.nan).fillna(0).clip(lower=0)

# Fix all FLOW_FEATURES inf values in one go
for feat in FLOW_FEATURES:
    if feat in df.columns:
        df[feat] = pd.to_numeric(df[feat], errors="coerce").replace(
            [np.inf, -np.inf], np.nan
        ).fillna(0).clip(lower=0)

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle("Dataset Overview", fontsize=16, fontweight="bold")

# Class distribution
ax = axes[0, 0]
df["label"].value_counts().plot(kind="bar", ax=ax, color=sns.color_palette("husl", 10))
ax.set_title("Class Distribution")
ax.set_xlabel("")
ax.tick_params(axis="x", rotation=45)

# Packet size distribution
ax = axes[0, 1]
for label in df["label"].unique()[:5]:
    subset = df[df["label"] == label]
    ax.hist(subset["fwd_pkt_len_mean"], alpha=0.6, label=label, bins=30)
ax.set_title("Fwd Packet Length Distribution")
ax.legend(fontsize=7)

# IAT distribution
ax = axes[0, 2]
for label in df["label"].unique()[:5]:
    subset = df[df["label"] == label]
    ax.hist(np.log1p(subset["iat_mean"]), alpha=0.6, label=label, bins=30)
ax.set_title("IAT Mean Distribution (log scale)")
ax.legend(fontsize=7)

# Flow bytes/sec — cap at 95th percentile for readability
ax = axes[1, 0]
viz_df = df.copy()
viz_df["flow_bytes_per_sec"] = viz_df["flow_bytes_per_sec"].clip(
    upper=viz_df["flow_bytes_per_sec"].quantile(0.95)
)
viz_df.boxplot(column="flow_bytes_per_sec", by="label", ax=ax)
ax.set_title("Flow Bytes/sec by Class")
ax.set_xlabel("")
plt.setp(ax.get_xticklabels(), rotation=45)

# PCA 2D
ax = axes[1, 1]
X_viz     = df[FLOW_FEATURES].fillna(0).values
scaler_viz = RobustScaler()
X_scaled  = scaler_viz.fit_transform(X_viz)
pca       = PCA(n_components=2, random_state=42)
X_2d      = pca.fit_transform(X_scaled)
labels_viz    = df["label"].values
unique_labels = np.unique(labels_viz)
colors        = plt.cm.tab10(np.linspace(0, 1, len(unique_labels)))
for lbl, color in zip(unique_labels, colors):
    mask = labels_viz == lbl
    ax.scatter(X_2d[mask, 0], X_2d[mask, 1], c=[color], label=lbl, alpha=0.5, s=10)
ax.set_title(f"PCA 2D (var={pca.explained_variance_ratio_.sum():.2f})")
ax.legend(fontsize=7)

# Feature correlation
ax = axes[1, 2]
corr = df[FLOW_FEATURES[:10]].corr()
sns.heatmap(corr, ax=ax, cmap="coolwarm", center=0, fmt=".1f", annot=False)
ax.set_title("Feature Correlation (first 10)")

plt.tight_layout()
plt.savefig("outputs/plots/dataset_overview.png", dpi=150, bbox_inches="tight")
plt.show()
print("Visualization saved.")

# ══════════════════════════════════════════════════════════════
# PREPROCESSING
# ══════════════════════════════════════════════════════════════
print("Preprocessing...")

# ── Hard caps on df BEFORE creating df_clean ──────────────────
HARD_CAPS = {
    "fwd_packet_count":   10_000,
    "bwd_packet_count":   10_000,
    "flow_bytes_per_sec": 125_000,
    "flow_pkts_per_sec":  10_000,
    "total_fwd_bytes":    100_000_000,
    "total_bwd_bytes":    100_000_000,
    "fwd_bwd_byte_ratio": 1_000,
    "fwd_pkt_len_max":    1_500,
    "bwd_pkt_len_max":    1_500,
    "fwd_iat_max":        60.0,
    "bwd_iat_max":        60.0,
    "iat_max":            60.0,
    "active_mean":        300.0,
    "idle_mean":          300.0,
    "flow_duration":      100.0,
}
for col, cap in HARD_CAPS.items():
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).clip(upper=cap)

# CIC-IDS-2017 flow_duration is in microseconds — convert to seconds
df["flow_duration"] = pd.to_numeric(
    df["flow_duration"], errors="coerce"
).fillna(0) / 1_000_000.0   # microseconds → seconds

# Re-apply cap after conversion
df["flow_duration"] = df["flow_duration"].clip(upper=100.0)

# Percentile clip at 95th
for feat in FLOW_FEATURES:
    if feat in df.columns:
        upper = pd.to_numeric(df[feat], errors="coerce").quantile(0.95)
        if upper > 0:
            df[feat] = pd.to_numeric(df[feat], errors="coerce").fillna(0).clip(upper=upper)

print(f"Hard caps done.")

# ── Create clean copy ──────────────────────────────────────────
df_clean = df[FLOW_FEATURES + ["label"]].copy()
df_clean = df_clean.replace([np.inf, -np.inf], np.nan)
df_clean = df_clean.dropna(subset=["label"])
print(f"Rows after cleaning: {len(df_clean)}")

# ── Log-transform skewed features ─────────────────────────────
LOG_FEATURES = [
    "fwd_packet_count", "bwd_packet_count",
    "flow_bytes_per_sec", "flow_pkts_per_sec",
    "total_fwd_bytes", "total_bwd_bytes",
    "fwd_pkt_len_mean", "bwd_pkt_len_mean",
    "fwd_pkt_len_std", "fwd_pkt_len_min", "fwd_pkt_len_max",
    "bwd_pkt_len_std", "bwd_pkt_len_min", "bwd_pkt_len_max",
    "fwd_bwd_byte_ratio", "fwd_bwd_pkt_ratio",
    "fwd_iat_mean", "bwd_iat_mean", "iat_mean",
    "fwd_iat_max", "bwd_iat_max", "iat_max",
    "fwd_iat_std", "bwd_iat_std", "iat_std",
    "active_mean", "idle_mean",
]
for feat in LOG_FEATURES:
    if feat in df_clean.columns:
        df_clean[feat] = np.log1p(
            pd.to_numeric(df_clean[feat], errors="coerce").fillna(0).clip(lower=0)
        )
print("Log transformation done.")

# ── Fix IAT min after log transform ───────────────────────────
df_clean["iat_min"]     = df_clean["iat_mean"].clip(lower=0)
df_clean["fwd_iat_min"] = df_clean["fwd_iat_mean"].clip(lower=0)
df_clean["bwd_iat_min"] = df_clean["bwd_iat_mean"].clip(lower=0)
df_clean["bwd_iat_std"] = df_clean["bwd_iat_mean"] * 0.5

# ── Extract features and labels ───────────────────────────────
X     = df_clean[FLOW_FEATURES].values.astype(np.float64)
y_raw = df_clean["label"].values

# ── Impute NaN with median ────────────────────────────────────
imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X)

# ── Encode labels ─────────────────────────────────────────────
le = LabelEncoder()
y  = le.fit_transform(y_raw)
CLASS_NAMES = list(le.classes_)
N_CLASSES   = len(CLASS_NAMES)
print(f"Classes ({N_CLASSES}): {CLASS_NAMES}")

# ── Train / val / test split ───────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.125, random_state=RANDOM_STATE, stratify=y_train
)

# ── Scale ─────────────────────────────────────────────────────
scaler  = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)

print(f"\nTrain: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")
print(f"X_train max: {X_train.max():.4f}")
print(f"X_train min: {X_train.min():.4f}")
print(f"X_train mean: {X_train.mean():.4f}")

if X_train.max() > 50:
    print("\n⚠️  WARNING: X_train max still high — check feature derivation")
else:
    print("\n✅ Scaling looks clean — safe to train models")

# ── Drop unlearnable classes ───────────────────────────────────
DROP_CLASSES  = ["Infiltration"]
existing_drop = [c for c in DROP_CLASSES if c in CLASS_NAMES]

if existing_drop:
    print(f"\nDropping low-sample classes: {existing_drop}")

    mask_train = ~np.isin(le.inverse_transform(y_train), existing_drop)
    mask_val   = ~np.isin(le.inverse_transform(y_val),   existing_drop)
    mask_test  = ~np.isin(le.inverse_transform(y_test),  existing_drop)

    X_train_f  = X_train[mask_train]
    y_train_f  = y_train[mask_train]
    X_val_f    = X_val[mask_val]
    y_val_f    = y_val[mask_val]
    X_test_f   = X_test[mask_test]
    y_test_f   = y_test[mask_test]

    le2       = LabelEncoder()
    y_train_f = le2.fit_transform(le.inverse_transform(y_train_f))
    y_val_f   = le2.transform(le.inverse_transform(y_val_f))
    y_test_f  = le2.transform(le.inverse_transform(y_test_f))

    CLASS_NAMES_F = list(le2.classes_)
    N_CLASSES_F   = len(CLASS_NAMES_F)

    print(f"Filtered classes ({N_CLASSES_F}): {CLASS_NAMES_F}")
    print(f"Train: {X_train_f.shape}, Val: {X_val_f.shape}, Test: {X_test_f.shape}")
    print("\nClass distribution in test set:")
    unique, counts = np.unique(y_test_f, return_counts=True)
    for cls, cnt in zip(CLASS_NAMES_F, counts):
        print(f"  {cls:<20} {cnt}")
else:
    X_train_f,  y_train_f  = X_train,  y_train
    X_val_f,    y_val_f    = X_val,    y_val
    X_test_f,   y_test_f   = X_test,   y_test
    le2           = le
    CLASS_NAMES_F = CLASS_NAMES
    N_CLASSES_F   = N_CLASSES
    print("No classes dropped.")

# ── Save preprocessors ────────────────────────────────────────
Path("outputs/models").mkdir(parents=True, exist_ok=True)
joblib.dump(scaler,        "outputs/models/scaler.pkl")
joblib.dump(le,            "outputs/models/label_encoder.pkl")
joblib.dump(le2,           "outputs/models/label_encoder_filtered.pkl")
joblib.dump(imputer,       "outputs/models/imputer.pkl")
joblib.dump(FLOW_FEATURES, "outputs/models/feature_names.pkl")
print("\nPreprocessors saved.")

feature_mins = X_train.min(axis=0)
print("Features with scaled min < -10:")
for i, mn in enumerate(feature_mins):
    if mn < -10:
        print(f"  {FLOW_FEATURES[i]:<30} min={mn:.2f}")

import pandas as pd
import numpy as np

print("=== FEATURE QUALITY CHECK ===\n")

# 1. How many features are near-constant (low variance = useless to SVM)
feature_stds = X_train.std(axis=0)
low_var = [(FLOW_FEATURES[i], round(feature_stds[i], 4))
           for i in range(len(FLOW_FEATURES)) if feature_stds[i] < 0.1]
print(f"Low-variance features (std < 0.1): {len(low_var)}")
for name, std in low_var:
    print(f"  {name}: std={std}")

# 2. Check actual value ranges after scaling
print(f"\nX_train max: {X_train.max():.2f}")
print(f"X_train min: {X_train.min():.2f}")
print(f"X_train mean: {X_train.mean():.4f}")

# 3. Check class separability — are classes actually different in feature space?
print("\n=== MEAN FEATURE VALUES PER CLASS (top 5 features) ===")
df_check = pd.DataFrame(X_train, columns=FLOW_FEATURES)
df_check["label"] = le.inverse_transform(y_train)
print(df_check.groupby("label")[
    ["fwd_packet_count", "total_fwd_bytes", "flow_duration",
     "fwd_pkt_len_mean", "flow_bytes_per_sec"]
].mean().round(2).to_string())

# 4. Check if derived features are all identical (no variance between classes)
print("\n=== DERIVED FEATURE VARIANCE CHECK ===")
derived = ["fwd_pkt_len_std", "fwd_pkt_len_min", "fwd_pkt_len_max",
           "active_mean", "idle_mean", "header_ratio", "payload_ratio"]
df_check2 = pd.DataFrame(X_train, columns=FLOW_FEATURES)
df_check2["label"] = le.inverse_transform(y_train)
for feat in derived:
    vals = df_check2[feat]
    print(f"  {feat}: std={vals.std():.4f}, unique={vals.nunique()}")

feature_maxes = X_train.max(axis=0)
feature_mins  = X_train.min(axis=0)

print("Features with scaled max > 20 or min < -5:")
for i, (mx, mn) in enumerate(zip(feature_maxes, feature_mins)):
    if mx > 20 or mn < -5:
        print(f"  {FLOW_FEATURES[i]:<30} max={mx:.2f}, min={mn:.2f}")

print("\nAll feature maxes:")
for i, mx in enumerate(feature_maxes):
    print(f"  {FLOW_FEATURES[i]:<30} max={mx:.2f}")

print(f"X_train_f shape:   {X_train_f.shape}")
print(f"y_train_f unique:  {np.unique(y_train_f)}")
print(f"y_train_f classes: {le2.inverse_transform(np.unique(y_train_f))}")
print(f"X_test_f shape:    {X_test_f.shape}")
print(f"y_test_f unique:   {np.unique(y_test_f)}")
print(f"y_test_f classes:  {le2.inverse_transform(np.unique(y_test_f))}")
print(f"CLASS_NAMES_F:     {CLASS_NAMES_F}")
print(f"N_CLASSES_F:       {N_CLASSES_F}")

# ══════════════════════════════════════════════════════════════
# UNSUPERVISED: K-Means
# ══════════════════════════════════════════════════════════════
print("Running K-Means clustering...")

# ── Elbow method to find optimal k ────────────────────────────
k_range    = range(2, 15)
inertias   = []
silhouettes = []

for k in k_range:
    km     = KMeans(n_clusters=k, n_init=10, random_state=RANDOM_STATE, max_iter=300)
    labels = km.fit_predict(X_train_f)
    inertias.append(km.inertia_)
    if len(np.unique(labels)) > 1:
        sil = silhouette_score(X_train_f, labels, sample_size=min(3000, len(X_train_f)))
        silhouettes.append(sil)
    else:
        silhouettes.append(0)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
ax1.plot(list(k_range), inertias, "bo-", linewidth=2, markersize=8)
ax1.set_xlabel("k"); ax1.set_ylabel("Inertia"); ax1.set_title("Elbow Curve")
ax1.grid(True, alpha=0.3)

ax2.plot(list(k_range), silhouettes, "rs-", linewidth=2, markersize=8)
ax2.set_xlabel("k"); ax2.set_ylabel("Silhouette Score"); ax2.set_title("Silhouette Scores")
ax2.grid(True, alpha=0.3)

optimal_k = list(k_range)[np.argmax(silhouettes)]
ax2.axvline(x=optimal_k, color="green", linestyle="--", label=f"Optimal k={optimal_k}")
ax2.legend()

plt.tight_layout()
plt.savefig("outputs/plots/kmeans_elbow.png", dpi=150, bbox_inches="tight")
plt.show()
print(f"Optimal k by silhouette: {optimal_k}")

# ── Fit K-Means with optimal k ────────────────────────────────
kmeans    = KMeans(n_clusters=optimal_k, n_init=20, max_iter=500, random_state=RANDOM_STATE)
kmeans.fit(X_train_f)
km_labels = kmeans.predict(X_test_f)

# ── Evaluate ──────────────────────────────────────────────────
if len(np.unique(km_labels)) > 1:
    sil = silhouette_score(X_test_f, km_labels, sample_size=min(5000, len(X_test_f)))
    ari = adjusted_rand_score(y_test_f, km_labels)
    print(f"K-Means Results:")
    print(f"  Silhouette Score:      {sil:.4f}")
    print(f"  Adjusted Rand Index:   {ari:.4f}")
    print(f"  Clusters found:        {len(np.unique(km_labels))}")

# ── PCA fitted on X_train_f — used by DBSCAN cell too ─────────
pca2 = PCA(n_components=2, random_state=42)
pca2.fit(X_train_f)                        # fit on train only
X_test_2d = pca2.transform(X_test_f)      # transform test

# ── Cluster visualization ─────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

colors = plt.cm.tab20(np.linspace(0, 1, optimal_k))
for i, c in enumerate(colors):
    mask = km_labels == i
    ax1.scatter(
        X_test_2d[mask, 0], X_test_2d[mask, 1],
        c=[c], label=f"Cluster {i}", alpha=0.5, s=15
    )
ax1.set_title("K-Means Clusters (PCA)")
ax1.legend(fontsize=7, bbox_to_anchor=(1.05, 1))

true_colors = plt.cm.tab10(np.linspace(0, 1, N_CLASSES_F))
for i, (cls, c) in enumerate(zip(CLASS_NAMES_F, true_colors)):
    mask = y_test_f == i
    ax2.scatter(
        X_test_2d[mask, 0], X_test_2d[mask, 1],
        c=[c], label=cls, alpha=0.5, s=15
    )
ax2.set_title("True Labels (PCA)")
ax2.legend(fontsize=7, bbox_to_anchor=(1.05, 1))

plt.tight_layout()
plt.savefig("outputs/plots/kmeans_clusters.png", dpi=150, bbox_inches="tight")
plt.show()

joblib.dump(kmeans, "outputs/models/kmeans_model.pkl")
print("K-Means model saved.")

# ══════════════════════════════════════════════════════════════
# UNSUPERVISED: DBSCAN
# ══════════════════════════════════════════════════════════════
from sklearn.neighbors import NearestNeighbors

# Sample from filtered training data
sample_size = min(5000, len(X_train_f))
idx         = np.random.choice(len(X_train_f), sample_size, replace=False)
X_sample    = X_train_f[idx]

# ── Find optimal eps via k-distance plot ──────────────────────
n_neighbors = 10
nn = NearestNeighbors(n_neighbors=n_neighbors)
nn.fit(X_sample)
distances, _ = nn.kneighbors(X_sample)
k_distances  = np.sort(distances[:, -1])

# Find elbow
diffs      = np.diff(k_distances)
elbow_idx  = np.argmax(diffs)
suggested_eps = float(k_distances[elbow_idx])

plt.figure(figsize=(8, 5))
plt.plot(k_distances)
plt.axvline(
    x=elbow_idx, color="red", linestyle="--",
    label=f"Elbow → eps≈{suggested_eps:.3f}"
)
plt.xlabel("Points sorted by distance")
plt.ylabel(f"{n_neighbors}-NN distance")
plt.title("DBSCAN eps selection (k-distance graph)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("outputs/plots/dbscan_eps.png", dpi=150, bbox_inches="tight")
plt.show()
print(f"Suggested eps: {suggested_eps:.4f}")

# ── Fit DBSCAN ────────────────────────────────────────────────
dbscan    = DBSCAN(eps=max(0.3, suggested_eps), min_samples=10, n_jobs=-1)
db_labels = dbscan.fit_predict(X_sample)

n_clusters = len(set(db_labels)) - (1 if -1 in db_labels else 0)
n_noise    = (db_labels == -1).sum()
print(f"DBSCAN Results:")
print(f"  Clusters found: {n_clusters}")
print(f"  Noise points:   {n_noise} ({n_noise/len(db_labels)*100:.1f}%)")

# ── Visualization ─────────────────────────────────────────────
# pca2 must already be fitted on X_train_f from the K-Means cell
# If running this cell standalone, refit pca2 here
if 'pca2' not in dir() or pca2 is None:
    pca2 = PCA(n_components=2, random_state=42)
    pca2.fit(X_train_f)

X_sample_2d = pca2.transform(X_sample)
fig, ax     = plt.subplots(figsize=(10, 7))
unique_db   = np.unique(db_labels)
colors      = plt.cm.tab20(np.linspace(0, 1, max(len(unique_db), 1)))

for label, color in zip(unique_db, colors):
    mask = db_labels == label
    name = "Noise" if label == -1 else f"Cluster {label}"
    ax.scatter(
        X_sample_2d[mask, 0], X_sample_2d[mask, 1],
        c=[color], label=name,
        alpha=0.6, s=10 if label != -1 else 5
    )

ax.set_title("DBSCAN Clusters (PCA)")
ax.legend(fontsize=7, bbox_to_anchor=(1.05, 1))
plt.tight_layout()
plt.savefig("outputs/plots/dbscan_clusters.png", dpi=150, bbox_inches="tight")
plt.show()

joblib.dump(dbscan, "outputs/models/dbscan_model.pkl")
print("DBSCAN model saved.")

# ══════════════════════════════════════════════════════════════
# SUPERVISED: SVM
# ══════════════════════════════════════════════════════════════
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

print("Training SVM (RBF kernel)...")
svm = SVC(
    kernel="rbf", C=10.0,       # increased from 1.0
    gamma="scale",
    probability=True,
    class_weight="balanced",
    random_state=RANDOM_STATE,
    max_iter=2000
)
svm.fit(X_train_f, y_train_f)
print("SVM training complete.")

y_pred_svm = svm.predict(X_test_f)
y_prob_svm = svm.predict_proba(X_test_f)

svm_acc = accuracy_score(y_test_f, y_pred_svm)
svm_f1  = f1_score(y_test_f, y_pred_svm, average="weighted", zero_division=0)
print(f"\\nSVM Results:")
print(f"  Accuracy: {svm_acc:.4f}")
print(f"  F1 (weighted): {svm_f1:.4f}")
print("\\nClassification Report:")
print(classification_report(y_test_f, y_pred_svm, target_names=CLASS_NAMES_F, zero_division=0))

# Confusion matrix
cm_svm = confusion_matrix(y_test_f, y_pred_svm)
plt.figure(figsize=(10, 8))
sns.heatmap(cm_svm, annot=True, fmt="d", cmap="Blues",
            xticklabels=CLASS_NAMES_F, yticklabels=CLASS_NAMES_F)
plt.title("SVM Confusion Matrix", fontsize=14, fontweight="bold")
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.tight_layout()
plt.savefig("outputs/plots/svm_confusion_matrix.png", dpi=150, bbox_inches="tight")
plt.show()

joblib.dump({"model": svm, "class_names": CLASS_NAMES_F}, "outputs/models/svm_model.pkl")
print("SVM saved.")

# ══════════════════════════════════════════════════════════════
# SUPERVISED: Random Forest
# ══════════════════════════════════════════════════════════════
print("Training Random Forest...")
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_split=5,
    class_weight="balanced",
    random_state=RANDOM_STATE,
    n_jobs=-1
)
rf.fit(X_train_f, y_train_f)
print("Random Forest training complete.")

y_pred_rf = rf.predict(X_test_f)
rf_acc    = accuracy_score(y_test_f, y_pred_rf)
rf_f1     = f1_score(y_test_f, y_pred_rf, average="weighted", zero_division=0)

print(f"\nRandom Forest Results:")
print(f"  Accuracy:      {rf_acc:.4f}")
print(f"  F1 (weighted): {rf_f1:.4f}")
print("\nClassification Report:")
print(classification_report(
    y_test_f, y_pred_rf,
    target_names=CLASS_NAMES_F,
    zero_division=0
))

# ── Feature importance ─────────────────────────────────────────
importances = rf.feature_importances_
indices     = np.argsort(importances)[::-1][:15]

plt.figure(figsize=(10, 6))
plt.barh(range(len(indices)), importances[indices], color="steelblue")
plt.yticks(range(len(indices)), [FLOW_FEATURES[i] for i in indices])
plt.gca().invert_yaxis()
plt.xlabel("Importance Score")
plt.title("Top 15 Feature Importances (Random Forest)", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("outputs/plots/rf_feature_importance.png", dpi=150, bbox_inches="tight")
plt.show()

# ── Confusion matrix ───────────────────────────────────────────
cm_rf = confusion_matrix(y_test_f, y_pred_rf)
plt.figure(figsize=(10, 8))
sns.heatmap(
    cm_rf, annot=True, fmt="d", cmap="Greens",
    xticklabels=CLASS_NAMES_F,
    yticklabels=CLASS_NAMES_F
)
plt.title("Random Forest Confusion Matrix", fontsize=14, fontweight="bold")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.savefig("outputs/plots/rf_confusion_matrix.png", dpi=150, bbox_inches="tight")
plt.show()

# ── Per-class breakdown ────────────────────────────────────────
print("\nPer-class breakdown:")
print(f"{'Class':<20} {'Correct':>8} {'Total':>8} {'Accuracy':>10}")
print("-" * 50)
for i, cls in enumerate(CLASS_NAMES_F):
    mask    = y_test_f == i
    correct = (y_pred_rf[mask] == y_test_f[mask]).sum()
    total   = mask.sum()
    acc     = correct / total if total > 0 else 0
    print(f"{cls:<20} {correct:>8} {total:>8} {acc:>10.2%}")

joblib.dump(
    {"model": rf, "class_names": CLASS_NAMES_F, "feature_names": FLOW_FEATURES},
    "outputs/models/rf_model.pkl"
)
print("\nRandom Forest saved.")

# ══════════════════════════════════════════════════════════════
# DEEP LEARNING: CNN on Flow Feature Matrices
# ══════════════════════════════════════════════════════════════

WINDOW_SIZE = 20

def to_cnn_matrix_sorted(X, y, window_size=20):
    """Sort by label first so each window contains only one class."""
    sort_idx  = np.argsort(y, kind='stable')
    X_sorted  = X[sort_idx]
    y_sorted  = y[sort_idx]
    n_windows = len(X_sorted) // window_size
    X_w       = X_sorted[:n_windows * window_size].reshape(
                    n_windows, window_size, X.shape[1])
    y_w       = y_sorted[:n_windows * window_size:window_size]
    return X_w[..., np.newaxis], y_w

# ── Convert filtered data to CNN windows ──────────────────────
X_train_cnn, y_train_cnn = to_cnn_matrix_sorted(X_train_f, y_train_f, WINDOW_SIZE)
X_val_cnn,   y_val_cnn   = to_cnn_matrix_sorted(X_val_f,   y_val_f,   WINDOW_SIZE)
X_test_cnn,  y_test_cnn  = to_cnn_matrix_sorted(X_test_f,  y_test_f,  WINDOW_SIZE)

input_shape = X_train_cnn.shape[1:]
print(f"CNN input shape:  {input_shape}")
print(f"Train windows:    {X_train_cnn.shape[0]}")
print(f"Val windows:      {X_val_cnn.shape[0]}")
print(f"Test windows:     {X_test_cnn.shape[0]}")
print(f"Classes:          {CLASS_NAMES_F}")

# ── Verify window labels are clean ────────────────────────────
print("\nWindow label distribution (train):")
unique_w, counts_w = np.unique(y_train_cnn, return_counts=True)
for cls_idx, cnt in zip(unique_w, counts_w):
    print(f"  {CLASS_NAMES_F[cls_idx]:<20} {cnt} windows")

# ── Build CNN ─────────────────────────────────────────────────
def build_cnn(input_shape, n_classes):
    inputs = keras.Input(shape=input_shape, name="flow_matrix")
    x      = inputs

    for filters in [32, 64, 128]:
        x = layers.Conv2D(filters, (3, 1), padding="same", activation="relu")(x)
        x = layers.BatchNormalization()(x)
        x = layers.Conv2D(filters, (3, 1), padding="same", activation="relu")(x)
        x = layers.BatchNormalization()(x)
        x = layers.MaxPooling2D((2, 1))(x)   # pool time axis only
        x = layers.Dropout(0.15)(x)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(n_classes, activation="softmax")(x)

    model = keras.Model(inputs, outputs, name="TrafficCNN")
    model.compile(
        optimizer=keras.optimizers.Adam(0.001),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

cnn_model = build_cnn(input_shape, N_CLASSES_F)
cnn_model.summary()

# ── Class weights ─────────────────────────────────────────────
unique_c, counts_c = np.unique(y_train_cnn, return_counts=True)
class_weights = {
    int(c): float(len(y_train_cnn) / (N_CLASSES_F * cnt))
    for c, cnt in zip(unique_c, counts_c)
}
print(f"\nClass weights: {class_weights}")

# ── Callbacks ─────────────────────────────────────────────────
callbacks = [
    EarlyStopping(
        monitor="val_accuracy", patience=10,
        restore_best_weights=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss", factor=0.5,
        patience=5, min_lr=1e-6, verbose=1
    ),
    ModelCheckpoint(
        "outputs/models/cnn_best.h5",
        monitor="val_accuracy",
        save_best_only=True, verbose=0
    ),
]

# ── Train ─────────────────────────────────────────────────────
print("\nTraining CNN...")
history = cnn_model.fit(
    X_train_cnn, y_train_cnn,
    validation_data=(X_val_cnn, y_val_cnn),
    epochs=50,
    batch_size=64,
    callbacks=callbacks,
    class_weight=class_weights,
    verbose=1
)

# ── Evaluate ──────────────────────────────────────────────────
y_pred_cnn = np.argmax(cnn_model.predict(X_test_cnn), axis=1)
cnn_acc    = accuracy_score(y_test_cnn, y_pred_cnn)
cnn_f1     = f1_score(y_test_cnn, y_pred_cnn, average="weighted", zero_division=0)

print(f"\nCNN Results:")
print(f"  Accuracy:      {cnn_acc:.4f}")
print(f"  F1 (weighted): {cnn_f1:.4f}")
print("\nClassification Report:")
print(classification_report(
    y_test_cnn, y_pred_cnn,
    target_names=CLASS_NAMES_F,
    zero_division=0
))

# ── Training history plots ─────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
ax1.plot(history.history["loss"],     label="Train Loss")
ax1.plot(history.history["val_loss"], label="Val Loss")
ax1.set_title("Loss")
ax1.legend()
ax1.set_xlabel("Epoch")

ax2.plot(history.history["accuracy"],     label="Train Acc")
ax2.plot(history.history["val_accuracy"], label="Val Acc")
ax2.set_title("Accuracy")
ax2.legend()
ax2.set_xlabel("Epoch")

plt.suptitle("CNN Training History", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("outputs/plots/cnn_training_history.png", dpi=150)
plt.show()

# ── Confusion matrix ───────────────────────────────────────────
cm_cnn = confusion_matrix(y_test_cnn, y_pred_cnn)
plt.figure(figsize=(10, 8))
sns.heatmap(
    cm_cnn, annot=True, fmt="d", cmap="Oranges",
    xticklabels=CLASS_NAMES_F,
    yticklabels=CLASS_NAMES_F
)
plt.title("CNN Confusion Matrix", fontsize=14, fontweight="bold")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.savefig("outputs/plots/cnn_confusion_matrix.png", dpi=150)
plt.show()

# ── Save ──────────────────────────────────────────────────────
cnn_model.save("outputs/models/cnn_model.keras")
with open("outputs/models/cnn_meta.json", "w") as f:
    json.dump({
        "class_names":  CLASS_NAMES_F,
        "input_shape":  list(input_shape),
        "n_classes":    N_CLASSES_F,
        "window_size":  WINDOW_SIZE
    }, f)
print("CNN saved.")

# ══════════════════════════════════════════════════════════════
# MODEL COMPARISON SUMMARY
# ══════════════════════════════════════════════════════════════

results = {
    "SVM":          {"accuracy": svm_acc,  "f1_weighted": svm_f1},
    "Random Forest":{"accuracy": rf_acc,   "f1_weighted": rf_f1},
    "CNN":          {"accuracy": cnn_acc,  "f1_weighted": cnn_f1},
}

print("\n" + "="*50)
print("FINAL MODEL COMPARISON")
print("="*50)
print(f"{'Model':<20} {'Accuracy':>10} {'F1 (weighted)':>15}")
print("-"*50)
for model_name, metrics in results.items():
    print(f"{model_name:<20} {metrics['accuracy']:>10.4f} {metrics['f1_weighted']:>15.4f}")
print("="*50)

# Best model
best_model = max(results, key=lambda m: results[m]["f1_weighted"])
print(f"\n🏆 Best model: {best_model} (F1={results[best_model]['f1_weighted']:.4f})")
print(f"   Classes:    {CLASS_NAMES_F}")
print(f"   Test size:  {len(y_test_f)} samples")

# Bar chart comparison
models     = list(results.keys())
accuracies = [results[m]["accuracy"]    for m in models]
f1_scores  = [results[m]["f1_weighted"] for m in models]

x     = np.arange(len(models))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))
bars1 = ax.bar(x - width/2, accuracies, width, label="Accuracy",      color="steelblue")
bars2 = ax.bar(x + width/2, f1_scores,  width, label="F1 (weighted)", color="darkorange")

ax.set_ylabel("Score")
ax.set_title(
    f"Model Comparison — {len(CLASS_NAMES_F)} classes: {', '.join(CLASS_NAMES_F)}",
    fontsize=12, fontweight="bold"
)
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.legend()
ax.set_ylim(0, 1.1)

for bar in bars1 + bars2:
    ax.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.01,
        f"{bar.get_height():.3f}",
        ha="center", va="bottom", fontsize=9
    )

plt.tight_layout()
plt.savefig("outputs/plots/model_comparison.png", dpi=150)
plt.show()

# Save results to JSON
import json
with open("outputs/reports/model_comparison.json", "w") as f:
    json.dump({
        "results":      results,
        "best_model":   best_model,
        "classes":      CLASS_NAMES_F,
        "n_classes":    N_CLASSES_F,
        "test_samples": len(y_test_f)
    }, f, indent=2)
print("Comparison report saved.")

import os
import shutil
from pathlib import Path

drive_output = f"{PROJECT_DIR}/outputs"

if os.path.exists("/content/drive"):

    os.makedirs(drive_output, exist_ok=True)

    copied = 0
    skipped = 0

    for src_path in Path("outputs").rglob("*"):
        if src_path.is_file():
            dst_path = Path(drive_output) / src_path.relative_to("outputs")
            dst_path.parent.mkdir(parents=True, exist_ok=True)

            try:
                if not dst_path.exists() or not os.path.samefile(src_path, dst_path):
                    shutil.copy2(src_path, dst_path)
                    copied += 1
                else:
                    skipped += 1
            except Exception as e:
                print(f"  Could not copy {src_path.name}: {e}")

    print(f"✅ Saved to Google Drive: {drive_output}")
    print(f"   Files copied:  {copied}")
    print(f"   Files skipped: {skipped} (already up to date)")

    # Print what was saved
    print("\nSaved files:")
    for f in sorted(Path(drive_output).rglob("*")):
        if f.is_file():
            size = f.stat().st_size / 1024
            print(f"  {f.relative_to(drive_output)} ({size:.1f} KB)")

else:
    print("Drive not mounted. Files are in outputs/ on the Colab instance.")
    print("They will be lost when the session ends — mount Drive and rerun.")